### PR TITLE
Reformat , add n dimension point support 

### PR DESCRIPTION
**Pull request by 123avi**
Reformat , add n dimension point support . 
refactoring style , change add remove blank lines, spaces

### CODE REVIEW

**Comment by thesamet** [comment]
Thanks for cleaning it up. One more thing and we're ready to merge!

**Comment by thesamet** [comment]
Thanks for your contribution, it's merged. I have removed `dimensionalOrderingForVector` and updated the tests in 47a562219109c98b968275f7ab6ae5eaa9b273e6.

**Comment by thesamet** [comment]
Pushed v1.0.4 with this change.

**Comment by 123avi** [comment]
Thanks Yuval, very nice work !!!

**Pull request merged**
